# Generated by Django 5.2 on 2025-04-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_completed', models.DateField()),
                ('project_url', models.URLField(blank=True, null=True)),
                ('project_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
            ],
        ),
    ]
